### ISSUE TITLE
AuthFunc doesn't contain the FullMethod info

### ISSUE THREAD

**Issue by thincal** [grpc-ecosystem/go-grpc-middleware#150]
Hi,

If I want to use the `AuthFunc` to do the authorization *centrally*, it needs to know which RPC method invoked.

I know that `AuthFuncOverride` could be used to do it per service, but I have a central authorization module to do this.

So what can I do ?

Thanks,
Song

**Comment by ZachEddy** [comment]
@domgreen I ran in to a similar issue. Basically, the request `context` inside my `AuthFunc` doesn't provide enough information to authorize a given request. I would really like to have access to the request itself inside the `AuthFunc` I wrote.

To give you some background, my gRPC function looks something like this.
```
// GetPetByID returns information about a given pet in the pet store
func (s server) GetPetByID(ctx context.Context, req *pb. GetPetByIDRequest) (*pb. GetPetByIDResponse, error)
```
The `req` parameter contains an `id` field that uniquely identifies a pet in the database. With this in mind, my authorization logic is, _"can user XYZ allowed to get information about this pet ABC?"_

It turns out that `id` would be useful to have, but it's not inside the context.

Here are some general thoughts about how I should proceed. I would be interested to hear your input. 

- In addition to middleware, I should make an authorization check inside the service itself. The service implementation will have access to the `id` field (seems reasonable, but requires two round-trip calls to our central authorization service).

- Write my own authorization middleware that is basically identical to this repository, but `AuthFunc` will take `req` as an additional argument (not ideal, but I can import the `grpc_auth` package and use its helpers).

- Open a pull request to `go-grpc-middleware` that adds `req` to the `AuthFunc` type (break code for lots of people).

**Comment by seinshah** [comment]
@ZachEddy I also have the same requirement which would make the code more clear if I perform the complete authentication before calling the method. Since, some scenario need `req` and some need `info`, I'd suggest the following approach:

```go
type AuthFuncExtended func(ctx context.Context, req interface{}, fullMethodName string) (context.Context, error)

type ServiceAuthFuncOverrideExtended interface {
	AuthFuncOverride(ctx context.Context, req interface{}, fullMethodName string) (context.Context, error)
}

func UnaryServerInterceptorExtended(authFunc AuthFuncExtended) grpc.UnaryServerInterceptor {
	return func(ctx context.Context, req interface{}, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (interface{}, error) {
		var newCtx context.Context
		var err error
		if overrideSrv, ok := info.Server.(ServiceAuthFuncOverrideExtended); ok {
			newCtx, err = overrideSrv.AuthFuncOverrideExtended(ctx, req, info.FullMethod)
		} else {
			newCtx, err = authFunc(ctx, req, info.FullMethod)
		}
		if err != nil {
			return nil, err
		}
		return handler(newCtx, req)
	}
}
```

This would make the file larger but it is backward compatible.

FYI: PR above wouldn't have answered this requirement

**Comment by bwplotka** [comment]
So it would be relatively easily in v2 to extend authFunc to include callMeta. However for streaming calls, this wouldn't be that trivial.

Let us know if this is still relevant, we can reopen.
