### ISSUE TITLE
grpc_retry.WithMax(), how to use it properly? 

### ISSUE THREAD

**Issue by feliksik** [grpc-ecosystem/go-grpc-middleware#37]
in [this example](https://github.com/grpc-ecosystem/go-grpc-middleware/blob/e09588dad0e25a825cb25b7ee60ef98fbd5b9b36/retry/examples_test.go#L73), we see the following code: 

```
func Example_deadlinecall() error {
	client := pb_testproto.NewTestServiceClient(cc)
	pong, err := client.Ping(
		newCtx(5*time.Second),
		&pb_testproto.PingRequest{},
		grpc_retry.WithMax(3),
		grpc_retry.WithPerRetryTimeout(1*time.Second))
	if err != nil {
		return err
	}
	fmt.Printf("got pong: %v", pong)
	return nil
}
```

But when I use one of those "option modifiers" as grpc_retry.WithMax() in a client call, it fails with a [nullpointer exception](https://gist.github.com/feliksik/237513d3f48211b6b8d69e4c147aece2). This is because the [callOption](https://github.com/grpc-ecosystem/go-grpc-middleware/blob/93c7e4f58c808620c244098d9e0fcb095543b222/retry/options.go#L95) wasn't set. 

It seems to work well when I pass it as a modifier to the constructor of grpc_retry.UnaryClientInterceptor, such as [in the test](https://github.com/grpc-ecosystem/go-grpc-middleware/blob/e09588dad0e25a825cb25b7ee60ef98fbd5b9b36/retry/retry_test.go#L93). 

I do not yet fully understand the code architecture, and I don't know how a `grpc.CallOption` is to be usted. My question is: Am I overlooking something? Is the example just wrong? Or is the implementation wrong?

**Comment by mwitkow** [comment]
@feliksik In order to use the `grpc_retry` `CallOption`s within your code invocations, you *need* to use either the UnaryClient or ServerClient interceptors when you instantiate the connection (on `grpc.Dial`)

These interceptors are the things that actually drive the calling logic, and the `CallOptions` are just per-call overrides.

You spotted a bug that I have no immediate way of fixing. You see, the `CallOptions` interface in `grpc` itself has private methods. Which means one needs to resort to a hack:
 * the `grpc_retry.CallOption` anonymously implements the `grpc.CallOption` interface. However it doesn't implement the private `before` and `after` functions, because it can't.
 * the interceptors strip out these `grpc_retry.CallOptions` before passing them to the `grpc.invoker` call which relies on `before` and `after` being implemented.

As such, the code panics. Sadly there are two ways around this:
 * either make the `grpc_retry.CallOption` use one of the `Headers`, `Failfast`, `Peer` or `Trailers` `grpc.CallOptions` as parents, and thus potentially disable the ability to use one of them by the user
 * or work with upstream to implent `grpc.CallOptions.Noop`. I'll file a bug.

**Comment by mwitkow** [comment]
Let's see what upstream responds, this is a snippet of a test that will make it fail:

```go
func (s *RetrySuite) TestCallOptionsDontPanicWithoutMiddleware() {
	s.srv.resetFailingConfiguration(3, codes.DataLoss, noSleep) // see retriable_errors
	nonMiddlewareClient := s.NewClient()
	_, err := nonMiddlewareClient.Ping(s.SimpleCtx(), goodPing,
		grpc_retry.WithMax(5),
		//grpc_retry.WithBackoff(grpc_retry.BackoffLinear(1*time.Millisecond)),
		//grpc_retry.WithCodes(codes.Aborted, codes.InvalidArgument),
		//grpc_retry.WithPerRetryTimeout(30*time.Millisecond),
	)
	require.NoError(s.T(), err, "the third invocation should succeed")
}
```

**Comment by feliksik** [comment]
Thanks for the clear response! I'll just make sure to use an interceptor in Dial() then. 

When the NoopOption would be implemented upstream, I'm still not sure how the internals work to apply the grpc_retry.WithMax(5) magically to the correct interceptor... but I can work around that.

**Comment by mwitkow** [comment]
When the NoopOption is implemented, you will still need to have an interceptor implemented. A simple option is not going to be enough.

**Comment by mwitkow** [comment]
So it seems upstream has a PR for it:
https://github.com/grpc/grpc-go/pull/1244

So there's hope for a proper fix! :)

**Comment by mwitkow** [comment]
Yup, there's a fix for it upstream, and we'll wait for the 1.4 gRPC Go release.
