### ISSUE TITLE
Question: Opentracing here vs github.com/grpc-ecosystem/grpc-opentracing

### ISSUE THREAD

**Issue by feliksik** [grpc-ecosystem/go-grpc-middleware#42]
How does the opentracing part of this repo relate to https://github.com/grpc-ecosystem/grpc-opentracing/tree/master/go/otgrpc (otgrpc)? 

It look like both package build middleware, using https://github.com/opentracing/opentracing-go

Are they alternative implementations? Are you in touch with the authors of otgrpc?

**Comment by mwitkow** [comment]
So, the `otgrpc` implements only a Unary handler, and this implements `Streaming` as well, both for client and server-side. 

Both packages are indeed using `opentracing-go` since that is the official opentracing library for Go, and a lot of `Tracer` implementations are using it. As such, both pieces of middleware are agnostic as to what `Tracer` is used by the user: Zipkin, Jaeger, Stackdriver or whatever else.

The reason why this package is separate here is because it integrates with `grpc_ctx` and thus allows you to have traces tagged with, for example, fields extracted from the request.

@bhs, author of `otgrpc` for discussion context.

**Comment by sagikazarmark** [comment]
Would be nice to have a single place for such middleware, especially within the same organization.

**Comment by bhs** [comment]
@mwitkow just noticed this, sorry!

I believe that there's a PR to support Streaming with the `otgrpc` package... in any case, we (obviously) should not duplicate this effort in two places. Is there a reason that `grpc_ctx` support should/could not just be added to the `otgrpc` package?

**Comment by mwitkow** [comment]
@bhs well `grpc_ctx` is an internal package of the `go-grpc-middlewares`. That's the only reason.

Can you link me to the Streaming PR for otgrpc?

**Comment by bhs** [comment]
@mwitkow sure: https://github.com/grpc-ecosystem/grpc-opentracing/pull/25

**Comment by F21** [comment]
@bhs @mwitkow Are there any plans to join forces and merge the 2 middlewares?

**Comment by bhs** [comment]
@F21 

1. Apologies for my delay, I missed this `@bhs` :-/
2. There are no plans that I'm aware of; that doesn't mean it's a bad idea, just that people have other priorities. I generally like the idea of minimizing the scope of packages, and for that reason have some natural bias towards the tracing-specific `grpc-opentracing` repo's charter; that said, everything is a tradeoff and if there's a compelling reason to merge the two middlewares I'm open to hearing about it.

**Comment by dinfer** [comment]
Is there a method to get the span in grpc handler? the middleware creates a span, and I cannot log into it.

**Comment by bwplotka** [comment]
Seems not relevant, given tracing is no longer part of this repo (in `v2`), given OpenTelemetry maintains great interceptor.
