### ISSUE TITLE
Plan for new release?

### ISSUE THREAD

**Issue by karelbilek** [grpc-ecosystem/go-grpc-middleware#533]
The current release (v1.3.0) is quite old at this point

There was this issue, which hit me now, and is already solved in the master - #498 - but there might be more that I don't see.

Are there some plans for a new release?

**Comment by johanbrandhorst** [comment]
I believe we've mostly focused on v2, though that effort has unfortunately stalled somewhat. I don't know if we plan on making another release for v1. What do you think @bwplotka?

**Comment by aimuz** [comment]
@johanbrandhorst What else is missing in v2 now?

**Comment by johanbrandhorst** [comment]
I'm frankly not sure v2 is ever going to happen at this point. I know Bartek has been very busy and just started a new job and I don't have any particular love for this project and generally recommend users don't use it. I might take some time to revamp this to be a "templates" project rather than something people use as a library, but I'm also busy with other things. I'm sorry to the users who are stuck in limbo, but as I said I generally recommend that instead of depending on this project as a library, you copy the interceptors you want to your own codebase and modify as necessary. There are too many specific use cases for a generic library like this, I think.

**Comment by karelbilek** [comment]
looking at the number of "stars" and... just what I see in general, lots of people _actually do_ use this project.

If you don't plan to make new releases, maybe mark this project as deprecated then?

I don't want to sound too snarky, it's just too much in limbo :)

**Comment by karelbilek** [comment]
also I'm fine with "this is complete, we just accept bugfixes" that some projects do (like... logrus for example?), but as I linked above, there is actual memory leak fixed in master already that's not released, so that's an actual bug

**Comment by bwplotka** [comment]
I actually wanted to sit down on v2 this week 🙃 Let's see how if we can push this towards the finish line. The v2 is much more lightweight and allows writing your own "plugins/modules". 
 
 In the mean time I will do "last" (or one of lasts) v1 releases with right comms, no harm in that.

**Comment by bwplotka** [comment]
Here you go https://github.com/grpc-ecosystem/go-grpc-middleware/releases/tag/v1.4.0

**Comment by karelbilek** [comment]
Thank you!
