### ISSUE TITLE
Cannot import go-grpc prometheus v1 when using grpc-middleware v2

### ISSUE THREAD

**Issue by blabbbbb** [grpc-ecosystem/go-grpc-middleware#553]
I am using github.com/grpc-ecosystem/go-grpc-middleware/v2 and want to add prometheus in my project.
The README.md of https://github.com/grpc-ecosystem/go-grpc-middleware/tree/v2 says, run 
`go get github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus`

but here is what I got after running this command
`go: module github.com/grpc-ecosystem/go-grpc-middleware@upgrade found (v1.4.0), but does not contain package github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus`

**Comment by bwplotka** [comment]
Yes! This is because we forgot to tag release candidate for this new module (: 

Added https://github.com/grpc-ecosystem/go-grpc-middleware/releases/tag/providers%2Fprometheus%2Fv1.0.0-rc.0

so now `go get github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus@v1.0.0-rc.0` should work. Once we have v1.0.0 and above, it should work without specifying version 🤗

**Comment by blabbbbb** [comment]
thanks so much, it does work now🤗

**Comment by blabbbbb** [comment]
> Yes! This is because we forgot to tag release candidate for this new module (:
> 
> Added https://github.com/grpc-ecosystem/go-grpc-middleware/releases/tag/providers%2Fprometheus%2Fv1.0.0-rc.0
> 
> so now `go get github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus@v1.0.0-rc.0` should work. Once we have v1.0.0 and above, it should work without specifying version 🤗
thanks so much, it does work now🤗

**Comment by blabbbbb** [comment]
@bwplotka thanks so much, it does work now🤗
