### ISSUE TITLE
Support ignore logging for v2(already attached PR)

### ISSUE THREAD

**Issue by linhbkhn95** [grpc-ecosystem/go-grpc-middleware#649]
## Background
I just upgraded from v1 to v2. But I have a problem with the logging package.
Currently, I have not seen an ignore logging feature like v1 at v2.
## What did I do
So, I decided to make a PR at #648 to do it.
## Confirmation
Feel free to confirm that I have missed something about v2
Otherwise, Please review my PR for solving this problem as quickly as possible.
Sorry If my mistake. 
Many thanks,

**Comment by linhbkhn95** [comment]
@johanbrandhorst Please help me with this issue. I really appreciate that.

**Comment by msmith** [comment]
FYI: The README for v2 mentions that deciders were [intentionally removed](https://github.com/grpc-ecosystem/go-grpc-middleware/blob/main/README.md?plain=1#L114):
>All "deciders", so functions that decide what to do based on gRPC service name and method (aka "fullMethodName") are removed (!). Use [`github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/selector`](interceptors/selector) interceptor to select what method, type or service should use what interceptor.

However, I think the selector middleware is not a 100% replacement for deciders because they don't allow you to make a logging decision based on the error response. For example, I may want to only log a healthcheck rpc when it fails, but I don't think you can do that with the selector interceptor.

**Comment by linhbkhn95** [comment]
@msmith thank for your response
