### ISSUE TITLE
[Question] grpc_ctxtags without interceptor

### ISSUE THREAD

**Issue by sstarcher** [grpc-ecosystem/go-grpc-middleware#90]
Prior to looking into using the grpc_ctxtags middleware I was using the context myself to propagate the tags.  I have the grpc_ctxtags wired up for my grpc server interceptors, but I also have a separate worker that is not a grpc server and I'm not seeing an easy way to use a common chunk of code for the tags and logging with the grpc_ctxtags as it returns a no-op tag when it was not initialized with the interceptor and I'm not seeing any other way to initialize it.

**Comment by mwitkow** [comment]
Sorry, I'm, not sure I understand. 

Do you have a separate chunk of code  (not used in a gRPC handler) that you'd like to use with `grpc_logging` (zap or logrus) that you extract the code from and thus are missing context tags?

**Comment by sstarcher** [comment]
Yes, we have a chunk of code that does not interact with gPRC at all.  It is reading from a queue to process jobs.

**Comment by mwitkow** [comment]
I would highly recommend using a very similar pattern for that logger and storing the code in the context yourself. I.e. use the same pattern but not leverage the gRPC Logrus/Zapper code itself for the logging of that.

**Comment by snktagarwal** [comment]
I have a follow up question here. I am using the same grpc_ctxtags flow for storing various key-values in context. Although, I am not able to write tests for code which may need mocking of these key-value pairs since they don't go through a interceptor.

What is the advice on using in these tests?

Eg code:
`
func (t *TestSuite) TestXX() {
  ctx := context.Background()
  grpc_ctxtags.Extract(ctx).Set(key, value)
  testFunction(ctx)
}
`
Assuming the testFunction uses the key, it won't work with the grpc_ctxtags code. How do I make it work? Is it possible to create a ctx with the Tags key-value pair set properly?

**Comment by mwitkow** [comment]
Are you trying to assert that your code is applying tags correctly? 

If so, there's two cases: you're doing it in an interceptor of your own, or you're doing it in a request handler.

If you're doing it in an interceptor, I recommend using the test harness of this project to do that, and use the grpc_ctxtags interceptor in it's setup. If you're doing it in a request handler, there are other ways you can isolate the code and test it separately.

**Comment by ofpiyush** [comment]
> there are other ways you can isolate the code and test it separately.

What are the ways? A simple example would work.

The only way I can see now is to wrap `grpc_ctxtags` and use the wrap instead.
